version: '3.8'

services:
  nginx:
    image: nginx:1.27.0-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./infra/nginx/go-boier.conf:/etc/nginx/conf.d/go-boier.conf
      - ./infra/mkcert:/opt/mkcert
  mysql:
    image: mysql:8.0
    ports:
      - 3006:3006
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msx-mysql
    restart: always
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_DB_HOST=redis
      - REDIS_DB_PASSWORD=password
    volumes:
      - ./db/redis_data:/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    volumes:
        - ./db/rabbitmq_data/:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: password
  backend:
    working_dir: /go/src/github.com/quansolashi/golang-boierplate/backend
    depends_on:
      - mysql
      - redis
      - rabbitmq
    build: 
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - 3002:3002
      - 5001:5001
    volumes:
      - ./backend:/go/src/github.com/quansolashi/golang-boierplate/backend:cached
    env_file: ./backend/.env
    restart: always
    command: make dev