name: push image

on:
  workflow_call:
    inputs:
      environment:
        description: 'environment'
        type: string
        required: true
      image-tag:
        description: 'image tag'
        type: string
        required: true
    outputs:
      image-uri:
        description: 'image URI'
        value: ${{ jobs.push.outputs.image-uri }}

permissions:
  contents: read

jobs:
  push:
    name: push image
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend

    outputs:
      image-uri: ${{ steps.set-image-uri.outputs.image-uri }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Gcloud
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set IMAGE_URI
      id: set-image-uri
      run: |
        echo "DOCKERHUB_IMAGE_URL=${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY}/${IMAGE_NAME}" >> $GITHUB_ENV
        echo "image-uri=${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}" >> $GITHUB_OUTPUT
      env:
        DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY }}
        IMAGE_NAME: ${{ vars.IMAGE_NAME }}
        IMAGE_TAG: ${{ inputs.image-tag }}

    - name: Build
      run: |
        docker build -f ./Dockerfile -t ${DOCKERHUB_IMAGE_URL} .
        docker tag ${DOCKERHUB_IMAGE_URL} ${DOCKERHUB_IMAGE_URL}:${IMAGE_TAG}
      env:
        IMAGE_TAG: ${{ inputs.image-tag }}

    - name: Push Image to Docker Hub
      run: docker push ${DOCKERHUB_IMAGE_URL}:${IMAGE_TAG}
      env:
        IMAGE_TAG: ${{ inputs.image-tag }}
